-- 单行单列子查询
-- 1. 查询大于公司平均工资的员工姓名
SELECT EMPNO, ENAME, SAL FROM emp WHERE SAL >= (SELECT  AVG(SAL) FROM emp);
-- 2. 查询出工资比MARTIN还要高的全部雇员信息
SELECT * FROM emp WHERE SAL >= (SELECT  SAL FROM emp WHERE ENAME = 'MARTIN');

-- 多行单列子查询
-- 1. 需求: 查询工资等于部门经理的员工信息
SELECT SAL FROM emp WHERE JOB = 'MANAGER';
SELECT * FROM emp WHERE SAL IN (SELECT SAL FROM emp WHERE JOB = 'MANAGER');
SELECT * FROM emp WHERE SAL IN (2450,2850,2975);
-- 2. 需求: 查询工资等于任意部门经理的员工信息
SELECT * FROM emp WHERE SAL = ANY (SELECT SAL FROM emp WHERE JOB = 'MANAGER');
-- 3. 需求: 查询工资大于任意部门经理的员工信息
SELECT * FROM emp WHERE SAL > ANY (SELECT SAL FROM emp WHERE JOB = 'MANAGER');
-- 4. 需求: 查询工资小于任意部门经理的员工信息
SELECT * FROM emp WHERE SAL < ANY (SELECT SAL FROM emp WHERE JOB = 'MANAGER');

-- 多列子查询
-- 查询出每个部门的编号, 名称, 部门人数, 平均工资
SELECT d.DEPTNO, d.DNAME, COUNT(e.EMPNO), AVG(e.SAL) FROM emp e RIGHT JOIN dept d ON e.DEPTNO = d.DEPTNO GROUP BY d.DEPTNO, d.DNAME;
SELECT e.DEPTNO, COUNT(e.EMPNO), AVG(e.SAL) FROM emp e GROUP BY e.DEPTNO;
SELECT e.DEPTNO, COUNT(e.EMPNO) count, AVG(e.SAL) avg FROM emp e GROUP BY e.DEPTNO;
SELECT d.DNAME, temp.count, temp.avg FROM dept d LEFT JOIN (SELECT e.DEPTNO, COUNT(e.EMPNO) count, AVG(e.SAL) avg FROM emp e GROUP BY e.DEPTNO) temp ON d.DEPTNO = temp.DEPTNO;

-- UNION / UNION ALL
SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e LEFT JOIN dept d ON e.DEPTNO = d.DEPTNO;
SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e RIGHT JOIN dept d ON e.DEPTNO = d.DEPTNO;
SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e LEFT JOIN dept d ON e.DEPTNO = d.DEPTNO UNION SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e RIGHT JOIN dept d ON e.DEPTNO = d.DEPTNO;
SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e LEFT JOIN dept d ON e.DEPTNO = d.DEPTNO UNION ALL SELECT e.DEPTNO, e.ENAME, e.SAL, d.DEPTNO, d.DNAME FROM emp e RIGHT JOIN dept d ON e.DEPTNO = d.DEPTNO;