-- 隔离级别
-- 查看当前会话隔离级别
SELECT @@tx_isolation;
-- 查看系统隔离级别
SELECT @@global.tx_isolation;
-- 设置当前会话隔离级别
-- 脏读 / 不可重复度 / 幻读 / 第二类丢失更新
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- 不可重复度 / 幻读 / 第二类丢失更新
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- 第二类丢失更新
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- 无
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- 设置系统隔离级别
SET GLOBAL TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET GLOBAL TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET GLOBAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- 查看锁资源使用情况
SELECT * FROM information_schema.INNODB_LOCKS;
-- 查看锁等待
SELECT * FROM information_schema.INNODB_LOCK_WAITS;
-- 查看事务
SELECT * FROM information_schema.INNODB_TRX;

-- 悲观锁
BEGIN;
SELECT * FROM emp FOR UPDATE;
COMMIT;
ROLLBACK;

-- 乐观锁
SELECT version FROM emp where id = 1;
UPDATE emp SET name = 'coderZsq' , version = version + 1 WHERE id = 1 AND version = 1;

