-- 1. 按照职位分组, 求出每个职位的最高和最低工资
SELECT JOB, MAX(SAL), MIN(SAL) FROM emp GROUP BY JOB;
SELECT JOB, ENAME, MAX(SAL) FROM emp GROUP BY JOB, ENAME;
SELECT MAX(SAL), MIN(SAL) FROM emp GROUP BY JOB;
SELECT JOB, COUNT(EMPNO), AVG(SAL) FROM emp GROUP BY JOB;
-- 2. 查询出每一个部门员工的平均工资
SELECT DEPTNO, AVG(SAL) FROM emp GROUP BY DEPTNO;
-- 3. 查询平均工资高于2000的部门和其平均工资
SELECT DEPTNO, AVG(SAL) FROM emp GROUP BY DEPTNO HAVING AVG(SAL) >= 2000;
-- 4. 查询各个部门和岗位的平均工资
SELECT DEPTNO, JOB, AVG(SAL) FROM emp GROUP BY DEPTNO, JOB;
-- 5. 查询各个管理人员的平均工资, 其中最低工资不能低于1300, 不计算老板
SELECT MGR, AVG(SAL) FROM emp WHERE MGR IS NOT NULL AND SAL >=1300 GROUP BY MGR;
SELECT MGR, AVG(SAL) FROM emp WHERE MGR IS NOT NULL GROUP BY MGR HAVING AVG(SAL) >= 1300
SELECT MGR, AVG(SAL) a FROM emp WHERE MGR IS NOT NULL GROUP BY MGR HAVING a >= 1300
-- 6. 查询在80,81,82,83年各进公司多少人
SELECT EMPNO, ENAME, HIREDATE FROM emp;
SELECT EMPNO, ENAME, YEAR(HIREDATE) FROM emp;
-- SELECT YEAR(HIREDATE), COUNT(EMPNO) FROM emp GROUP BY YEAR(HIREDATE) HAVING YEAR(HIREDATE) IN ('1980', '1981', '1982', '1983');
SELECT YEAR(HIREDATE) y, COUNT(EMPNO) FROM emp GROUP BY y HAVING y IN ('1980', '1981', '1982', '1983');