package design_pattern.struct.adapter.case3;

public class CD { //这个类来自外部sdk，我们无权修改它的代码
    //...
    public static void staticFunction1() { //...
    }

    public void uglyNamingFunction2() { //...
    }

    public void tooManyParamsFunction3(int paramA, int paramB) { //...
    }

    public void lowPerformanceFunction4() { //...
    }
}