-- 多行函数
-- 查询所有员工每个月支付的平均工资及总工资
SELECT SUM(SAL) FROM emp;
SELECT SUM(SAL) / COUNT(EMPNO) FROM emp;
SELECT SUM(SAL), AVG(SAL) FROM emp;
-- 查询月薪在2000以上的员工总人数
SELECT COUNT(EMPNO) FROM emp;
SELECT COUNT(EMPNO) FROM emp WHERE SAL >= 2000;
SELECT COUNT(*) FROM emp;
SELECT COUNT(1) FROM emp;
SELECT COUNT(IF(SAL > 1000, 1, NULL)) FROM emp;
SELECT COUNT(EMPNO) FROM emp;
SELECT COUNT(COMM) FROM emp;
-- 查询员工最高工资和最低工资差距
SELECT MAX(SAL), MIN(SAL) FROM emp;
SELECT MAX(SAL) - MIN(SAL) FROM emp;

-- 单行函数
-- 字符函数
-- 把HelloWorld转换为全大写, 全小写
SELECT LOWER(ENAME) FROM emp;
SELECT UPPER(LOWER(ENAME)) FROM emp;
SELECT UPPER('HelloWorld');
SELECT UPPER('HelloWorld') FROM dual;
SELECT UPPER('HelloWorld'), LOWER('HelloWorld') FROM dual;
-- CONCAT
SELECT CONCAT(ENAME,'的工作是', JOB) FROM emp;
-- CHAR_LENGTH / LENGTH
SELECT CHAR_LENGTH('泉哥coderZsq') FROM dual;
SELECT LENGTH('泉哥coderZsq') FROM dual;
-- LAPD / RPAD
SELECT LPAD('ABC', 7, 'X'), LPAD('ABC', 5, 'X'), LPAD('ABC', 3, 'X'), LPAD('ABC', 1, 'X') FROM dual;
-- LTRIM / TRIM / RTRIM
SELECT LTRIM(' A B C '), RTRIM(' A B C '), TRIM(' A B C ') FROM dual;
-- REPLACE
SELECT REPLACE('https://github.com/coderzsq', 'z', 'Z') FROM dual;
-- SUBSTRING
SELECT SUBSTRING('ABCDEFG', 3) FROM dual;
SELECT SUBSTRING('ABCDEFG', 3, 3) FROM dual;

-- 数字函数
-- ABS / MOD
SELECT ABS(-17), ABS(17), MOD(10, 5), MOD(10, 9) FROM dual;
-- CEIL / FLOOR / ROUND / TRUNCATE
SELECT CEIL(0.5), CEIL(-1.5), CEIL(1.5) FROM dual;
SELECT FLOOR(0.5), FLOOR(-1.5), FLOOR(1.5) FROM dual;
SELECT ROUND(3.495) FROM dual;
SELECT ROUND(3.50) FROM dual;
SELECT ROUND(3.495, 1) FROM dual;
SELECT ROUND(3.495, 2) FROM dual;
SELECT ROUND(3.495, 3) FROM dual;
SELECT ROUND(3.495, 0) FROM dual;
SELECT ROUND(3.495, -1) FROM dual;

-- 日期函数
-- NOW()
SELECT NOW() FROM dual;
-- DATE_ADD / DATE_SUB
SELECT DATE_ADD(NOW(), INTERVAL 100 DAY);
SELECT DATE_ADD(NOW(), INTERVAL 100 YEAR);
SELECT DATE_ADD(NOW(), INTERVAL 1000 YEAR);
SELECT DATE_ADD(NOW(), INTERVAL 1000 HOUR);
SELECT DATE_SUB(NOW(), INTERVAL 100 DAY);
-- CURRENT_DATE / CURRENT_TIME
SELECT CURRENT_DATE(), CURRENT_TIME() FROM dual;
-- DATEDIFF
SELECT DATEDIFF(NOW(), '2000-01-01') FROM dual;
-- 获取日期时间某个段
SELECT NOW() FROM dual;
SELECT YEAR((NOW())) FROM dual;
SELECT * FROM emp WHERE YEAR(HIREDATE) = '1981';
-- UNIX_TIMESTAMP / FROM_UNIXTIME
SELECT UNIX_TIMESTAMP(NOW());
SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(NOW()));

-- 转换函数
-- 数字和字符串
SELECT FORMAT(123456.789,2) FROM dual;
-- 日期和字符串
SELECT DATE_FORMAT(NOW(), '%Y-%m-%d');
SELECT DATE_FORMAT(NOW(), '%Y/%m/%d');
SELECT STR_TO_DATE('2020/02/19', '%Y/%m/%d');